# Generated by Django 4.2.7 on 2026-04-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_family_gasto_family_familymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='data_competencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
